id: A84A38845
title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the Three
  Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
type: translation
pechas:
- I77B8643B
- I87AF7775
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:14.105139
  last_modified_at: 2023-01-04 13:02:14.105145
  collections:
  - Milarepa Series
  - Works of Tibetan Masters
alignment_to_base:
  I77B8643B/7EEF: C8DF
  I87AF7775/9D3D: C8DF
